# Generated by Django 5.1.4 on 2025-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=15),
        ),
    ]
