# Generated by Django 5.1.4 on 2025-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_downvotes_question_deleted_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='votes_type',
            field=models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], default='Upvote', max_length=200),
        ),
    ]
